export const action_type = {
    SELECTED_USER_TYPE: 'SELECTED_USER_TYPE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ALERT_SNACK_BAR: 'ALERT_SNACK_BAR',
    ADD_NEW_VIDEO: 'ADD_NEW_VIDEO',
    DELETE_NEW_VIDEO: 'DELETE_NEW_VIDEO',
    FETCH_VIDEO: 'FETCH_VIDEO',
    FETCH_FOOTER_VIDEO: 'FETCH_FOOTER_VIDEO',
    ADD_NEW_FOOTER_VIDEO: 'ADD_NEW_FOOTER_VIDEO',
    DELETE_FOOTER_VIDEO: 'DELETE_FOOTER_VIDEO',

    // CUSTOMER ACTION TYPE
    FETCH_CUSTOMERS: 'FETCH_CUSTOMERS',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    FETCH_CUSTOMER_BY_ID: 'FETCH_CUSTOMER_BY_ID',

    // WEB CAM CAPTURE ACTION TYPE
    ALLOW_CAMERA: 'ALLOW_CAMERA',
    ADD_AVAILABLE_CAMERAS: 'ADD_AVAILABLE_CAMERAS',
    SET_SELECTED_CAMERA: 'SET_SELECTED_CAMERA',
    SET_PERMISSION_STATUS: 'SET_PERMISSION_STATUS',
    ADD_CLIENT_PHOTO: 'ADD_CLIENT_PHOTO',
    RESET_CLIENT_PHOTO: 'RESET_CLIENT_PHOTO',
    DELETE_CLIENT_PHOTO: 'DELETE_CLIENT_PHOTO',
    RESET_PHOTOS: 'RESET_PHOTOS',
    FETCH_CLIENT: 'FETCH_CLIENT',
    FETCH_CLIENT_BY_ID: 'FETCH_CLIENT_BY_ID',
    ADD_CLIENT: 'ADD_CLIENT',
    SET_SELECT_CLIENT: 'SET_SELECT_CLIENT',
    DELETE_CLIENT: 'DELETE_CLIENT',
    CLIENT_UPDATE_MODAL_STATUS: 'CLIENT_UPDATE_MODAL_STATUS',
    SELECT_FOR_UPDATE_CLIENT: 'SELECT_FOR_UPDATE_CLIENT',
    SELECTED_CLIEND_DATA: 'SELECTED_CLIEND_DATA',
    UPDATE_CLIENT: 'UPDATE_CLIENT',
    CLIENT_ADD_MODAL_STATUS: 'CLIENT_ADD_MODAL_STATUS',

    // CAMERA VOICE ACTION TYPE
    FETCH_ALL_CAMERA_VOICE: 'FETCH_ALL_CAMERA_VOICE',
    FETCH_CAMERA_VOICE_BY_ID: 'FETCH_CAMERA_VOICE_BY_ID',
    ADD_CAMERA_VOICE: 'ADD_CAMERA_VOICE',
    UPDATE_CAMERA_VOICE: 'UPDATE_CAMERA_VOICE',
    DELETE_CAMERA_VOICE: 'DELETE_CAMERA_VOICE',

    // COLORING PAGE ACTION TYPE
    FETCH_ALL_COLORING_PAGE: 'FETCH_ALL_COLORING_PAGE',
    FETCH_COLORING_PAGE_BY_ID: 'FETCH_COLORING_PAGE_BY_ID',
    ADD_COLORING_PAGE: 'ADD_COLORING_PAGE',
    UPDATE_COLORING_PAGE: 'UPDATE_COLORING_PAGE',
    DELETE_COLORING_PAGE: 'DELETE_COLORING_PAGE',

    // CAMERA ACTION TYPE
    FETCH_ALL_CAMERA: 'FETCH_ALL_CAMERA',
    FETCH_CAMERA_BY_ID: 'FETCH_CAMERA_BY_ID',
    ADD_CAMERA: 'ADD_CAMERA',
    DELETE_CAMERA: 'DELETE_CAMERA',
    UPDATE_CAMERA: 'UPDATE_CAMERA',
}