export const action_type = {
    SELECTED_USER_TYPE: 'SELECTED_USER_TYPE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ALERT_SNACK_BAR: 'ALERT_SNACK_BAR',
    ADD_NEW_VIDEO: 'ADD_NEW_VIDEO',
    DELETE_NEW_VIDEO: 'DELETE_NEW_VIDEO',
    FETCH_VIDEO: 'FETCH_VIDEO',
    FETCH_FOOTER_VIDEO: 'FETCH_FOOTER_VIDEO',
    ADD_NEW_FOOTER_VIDEO: 'ADD_NEW_FOOTER_VIDEO',
    DELETE_FOOTER_VIDEO: 'DELETE_FOOTER_VIDEO',
    FETCH_CUSTOMERS: 'FETCH_CUSTOMERS',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    FETCH_CUSTOMER_BY_ID: 'FETCH_CUSTOMER_BY_ID'
}